language: php

php:
  - hhvm
  - 5.6
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: hhvm
    - php: 5.6

before_script:
  - composer self-update
  - composer install
  - cp phpunit.xml.dist phpunit.xml