version: "3"

services:
  nginx:
    container_name: nginx_caching_proxy
    image: webdevops/php-nginx:8.2-alpine
    working_dir: /app
    volumes:
        - ../../:/app
    ports:
      - 127.0.0.1:8090:80
    env_file:
      - ../.env/.env
    networks:
      - caching_proxy_net

networks:
  caching_proxy_net:
    driver: bridge